### ISSUE TITLE
The way queries are constructed leaves vulnerability to SQL injection

### ISSUE THREAD

**Issue by GenericAlias** [CSE403FindersKeepers/finders-keepers#12]
The way strings are concatenated in order to construct SQL queries for the database to execute could be taken advantage of by a malicious user in order to drop tables or attack in some other way using SQL injection. This issue could be resolved by looking into more secure ways to construct queries at the time of the feature complete release or if delays occur before the release candidate. This issue is not as severe for the demo but is something that should be addressed before considering an official release.

**Comment by dowelc** [comment]
I feel like we don't really care about this, but if everyone wants to fix it, we should upgrade this to high severity and assign it to someone
