### ISSUE TITLE
Emails currently not unique

### ISSUE THREAD

**Issue by GenericAlias** [CSE403FindersKeepers/finders-keepers#13]
In the database, it is currently possible to have duplicate emails for users, where different users share the same email. This is a design error that could lead to confusion and incorrect performance later on, and return data to users that does not belong to them. This should be fixed in time for the feature complete release in order to avoid bugs, but hopefully it should be simple to fix.

**Comment by dowelc** [comment]
@GenericAlias are we still trying to do this by feature complete? Should we enforce this thru DB or DB handler?
