### ISSUE TITLE
Wishlist needs work

### ISSUE THREAD

**Issue by khess-cse** [CSE403FindersKeepers/finders-keepers#26]
Wishlist is unintuitive and needs to be an actual list

**Comment by dowelc** [comment]
Clarify? @khess-cse

**Comment by khess-cse** [comment]
I just don't like how the wishlist is just a string of text, so I'm just
gonna work on it after we turn in our work tonight and make it an actual
list to give myself something to do

**Comment by khess-cse** [comment]
Wishlist improved
