### ISSUE TITLE
Accessing a trade holding a deleted item crashes the app

### ISSUE THREAD

**Issue by GenericAlias** [CSE403FindersKeepers/finders-keepers#29]
The application needs proper error handling to handle this case without crashing, which we hope to have in place in time for the release candidate.

**Comment by dowelc** [comment]
Okay I have a proposed solution for this: when a delete_item request is made, let's 
- check if it's involved in any trades and just remove it from that trade and 
-change the trade status to cancelled
Sound good? @GenericAlias @Jaredng @artemz2

**Comment by GenericAlias** [comment]
That sounds like it'll work

**Comment by dowelc** [comment]
Update: the front end does not support the status 'cancelled' so I am going to delete a trade for now when an item in it is deleted

**Comment by dowelc** [comment]
Okay actually I made it so it changes the status to '' and the FE logic groups it into the "rejected" category. The weird thing is when you click on the trade, it says "incoming" even though its in the rejected category. I'm going to work on fixing that.

**Comment by dowelc** [comment]
Fixed on BE & FE
